# _name = "bzd-notify"

[http]
endpoint = "0.0.0.0:3000"

[db]
endpoint = "postgres://postgres:postgres@0.0.0.0:5432/bzd_notify"

[nats]
endpoint = "0.0.0.0:4222"
stream = "bzd"

[clients.users]
endpoint = ""

[notify.messaging.messages]
subjects = ["bzd.messages.events.messages"]
consumer = "bzd-notify-notify-messages"

[notify.messaging.notify]
subject = "bzd.notify.notify"
